import time
text = """
ooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooooooooooooo
ooooooooiiiiiiiiiiiiiiiiiiioooooooooooo
ooooooiiiiiiiiiiiiiiiiiiiiiiiiooooooooo
oooiiiiiiiiiooooooooooooiiiiiiioooooooo
oooiiiiiioooooooooooooooooiiiiiiooooooo
oooiiiiioooooooooooooooooooiiiiioooooo
oooiiiiioooooooooooooooooooiiiiioooooo
oooiiiiioooooooooooooooooooiiiiioooooo
oooiiiiioooooooooooooooooooooooooooooo
oooiiiiioooooooooooooooooooooooooooooo
oooiiiiioooooooooooooooooooooooooooooo
oooiiiiioooooiiiiiiiiooooooooooooooooo
oooiiiiioooiiiiiiiiiiiiiooooooooooooo
oooiiiiioiiiiiiooooooiiiiiiioooooooooo
oooiiiiiiiiiooooooooooooiiiiiioooooooo
oooiiiiiooooooooooooooooooiiiiiioooooo
oooiiiioooooooooooooooooooooiiiiooooo
oooiiiioooooooooooooooooooooiiiiooooo
ooooiiiioooooooooooooooooooiiiiooooo
oooooiiiiiioooooooooooooooiiiiooooooo
ooooooooiiiiiiiiiiiiiiiiiiiioooooooo
ooooooooooiiiiiiiiiiiiiiiiiooooooooo
oooooooooooooooiiiiiiooooooooooooooo

oooooooooooooooooooooooooooooooooo 
oooooooooooooooooooooooooooooooooo
ooiiiiiiiiiiiiiiiiiiiiiiiiiiiiooo
ooiiiiiiiiiiiiiiiiiiiiiiiiiiioooo
ooiiiiooooooooooooooooooiiiiooooo
oooooooooooooooooooooooiiiioooooo
ooooooooooooooooooooooiiiiooooooo
oooooooooooooooooooooiiiiooooooo
ooooooooooooooooooooiiiioooooooo
oooooooooooooooooooiiiioooooooooo
ooooooooooooooooooiiiioooooooooo
oooooooooooooooooiiiioooooooooo
ooooooooooooooooiiiiooooooooooo
oooooooooooooooiiiiooooooooooo
ooooooooooooooiiiioooooooooooo
oooooooooooooiiiiooooooooooooo
ooooooooooooiiiiooooooooooooo
oooooooooooiiiioooooooooooooo
ooooooooooiiiiooooooooooooooo
oooooooooiiiioooooooooooooooo
oooooooooooooooooooooooooooo
"""



text02 = """

while True:
    print(text)
    time.sleep(1)